import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  form: { marginTop: 24 },
  formGroup: { marginBottom: 20 },
  label: { color: "#ccc", fontSize: 13, marginBottom: 6, fontWeight: "500" },
  input: {
    backgroundColor: "#1a1a1a",
    borderWidth: 1,
    borderColor: "#333",
    borderRadius: 8,
    color: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  inputError: { borderColor: "#c0392b" },
  textarea: { minHeight: 100 },
  hintText: { color: "#666", fontSize: 12, marginBottom: 8 },
  errorText: { color: "#c0392b", fontSize: 12, marginTop: 4 },
  radioRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  radio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#555",
    marginRight: 10,
  },
  radioSelected: { backgroundColor: "#fff", borderColor: "#fff" },
  radioLabel: { color: "#ccc", fontSize: 15 },
  checkboxRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#555",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  checkboxChecked: { backgroundColor: "#fff", borderColor: "#fff" },
  checkmark: { color: "#000", fontSize: 13, fontWeight: "700" },
  checkboxLabel: { flex: 1, color: "#aaa", fontSize: 13, lineHeight: 20 },
  submitButton: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  submitButtonText: { color: "#000", fontWeight: "600", fontSize: 15 },
  clearButton: {
    borderWidth: 1,
    borderColor: "#444",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
    marginBottom: 16,
  },
  clearButtonText: { color: "#666", fontSize: 14 },
  formFooter: {
    color: "#555",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 18,
  },
});
