import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  form: { marginTop: 24 },
  formGroup: { marginBottom: 20 },
  label: { fontSize: 13, marginBottom: 6, fontWeight: "500" },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  inputError: { borderColor: "#c0392b" },
  textarea: { minHeight: 100 },
  hintText: { fontSize: 12, marginBottom: 8 },
  errorText: { color: "#c0392b", fontSize: 12, marginTop: 4 },
  radioRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  radio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    marginRight: 10,
  },
  radioSelected: {},
  radioLabel: { fontSize: 15 },
  checkboxRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  checkboxChecked: {},
  checkmark: { fontSize: 13, fontWeight: "700" },
  checkboxLabel: { flex: 1, fontSize: 13, lineHeight: 20 },
  submitButton: {
    borderRadius: 8,
    padding: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  submitButtonText: { fontWeight: "600", fontSize: 15 },
  clearButton: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
    marginBottom: 16,
  },
  clearButtonText: { fontSize: 14 },
  formFooter: {
    fontSize: 12,
    textAlign: "center",
    lineHeight: 18,
  },
});
