import { StyleSheet } from "react-native";

const CARD_HEIGHT = 96;

export const styles = StyleSheet.create({
  card: {
    flexDirection: "row",
    alignItems: "center",
    height: CARD_HEIGHT,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e3e5ea",
    borderRadius: 14,
    overflow: "hidden",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    position: "relative",
  },
  imageContainer: {
    width: "25%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#eef0f4",
  },
  image: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 0,
  },
  infoContainer: {
    width: "75%",
    height: "100%",
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: 18,
    paddingVertical: 12,
  },
  title: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 14,
    color: "#657188",
    marginTop: 2,
  },
  year: {
    fontSize: 12,
    color: "#888",
    marginTop: 2,
  },
  rightActionContainer: {
    flexDirection: "row",
    height: CARD_HEIGHT - 14,
    alignItems: "center",
    marginVertical: 7,
    marginHorizontal: 10,
    gap: 6,
  },
  actionButton: {
    width: 56,
    height: 56,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    flexDirection: "column",
  },
  // SWIPE HINT styles
  swipeHintContainer: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 32,
    justifyContent: "center",
    alignItems: "flex-end",
    zIndex: 2,
  },
  swipeGradient: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    height: "100%",
    width: 24,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
  },
  swipeChevron: {
    position: "absolute",
    right: 7,
    top: "50%",
    marginTop: -9,
    opacity: 0.7,
  },
});
