export const TABLET_BREAKPOINT = 768;

export const MOBILE_GALLERY_ITEM_HEIGHT = 580;
export const TABLET_GALLERY_ITEM_HEIGHT = 720;

export const IMAGE_HEADER_HEIGHT = 50;

export const GALLERY_TITLE_HEIGHT = 33;

export const GALLERY_FOOTER_ROW_HEIGHT = 80;

export const MOBILE_PHOTOGRAPHER_ITEM_HEIGHT = 600;
export const TABLET_PHOTOGRAPHER_ITEM_HEIGHT = 800;
export const PHOTOGRAPHER_HEADER_IMAGE_WIDTH_RATIO = 0.7;
export const MOBILE_PHOTOGRAPHER_HEADER_HEIGHT_RATIO = 0.5;
export const TABLET_PHOTOGRAPHER_HEADER_HEIGHT_RATIO = 0.7;
export const PHOTOGRAPHER_GALLERY_YEAR_HEIGHT = 33;
export const PHOTOGRAPHER_GALLERY_DESCRIPTION_HEIGHT = 66;
export const PHOTOGRAPHER_GALLERY_FOOTER_HEIGHT = 90;
