import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#111" },
  content: { padding: 16, paddingBottom: 60 },
  centered: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#111" },
  header: { marginBottom: 24 },
  pageTitle: {
    fontSize: 36,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: -0.5,
  },
  pageSubTitle: { fontSize: 16, color: "#ccc", marginTop: 8, paddingHorizontal: 4 },
  intro: { fontSize: 15, color: "#aaa", lineHeight: 24, marginTop: 12 },
  shareButton: {
    marginTop: 16,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#555",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  shareButtonText: { color: "#ccc", fontSize: 13 },
  infoSection: { marginBottom: 32 },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "500",
    color: "#fff",
    borderLeftWidth: 3,
    borderLeftColor: "#888",
    paddingLeft: 12,
    marginBottom: 16,
  },
  infoCard: {
    backgroundColor: "#1e1e1e",
    borderWidth: 1,
    borderColor: "#333",
    borderRadius: 16,
    padding: 16,
  },
  bulletItem: { color: "#bbb", lineHeight: 24, marginBottom: 4 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  card: {
    backgroundColor: "#1a1a1a",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 8,
  },
  cardImageWrapper: {
    width: "100%",
    aspectRatio: 4 / 3,
    backgroundColor: "#222",
  },
  cardImage: { width: "100%", height: "100%" },
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#2a2a2a",
  },
  cardName: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
    padding: 12,
    paddingBottom: 4,
  },
  cardMeta: { flexDirection: "row", gap: 8, paddingHorizontal: 12, paddingBottom: 12 },
  cardMetaText: { color: "#888", fontSize: 12 },
  licenseText: { color: "#666", fontSize: 12 },
  emptyState: { color: "#666", fontStyle: "italic", marginBottom: 32 },
  errorText: { color: "#aaa", fontSize: 15, marginBottom: 16 },
  retryButton: {
    borderWidth: 1,
    borderColor: "#555",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: { color: "#ccc", fontSize: 14 },
  filtersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 20,
    marginBottom: 16,
  },
  pill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#444",
    borderRadius: 16,
    backgroundColor: "transparent",
  },
  pillActive: {
    borderColor: "#fff",
    backgroundColor: "#fff",
  },
  pillText: {
    color: "#888",
    fontSize: 13,
  },
  pillTextActive: {
    color: "#000",
    fontWeight: "600",
  },
  cardBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "rgba(0,0,0,0.65)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  cardBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "500",
  },
  ctaSection: {
    marginTop: 48,
    padding: 24,
    backgroundColor: "#1e1e1e",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#333",
  },
  ctaTitle: { fontSize: 22, fontWeight: "600", color: "#fff", marginBottom: 12 },
  ctaText: { color: "#aaa", lineHeight: 22, marginBottom: 12 },
  ctaButton: {
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#666",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  ctaButtonText: { color: "#fff", fontSize: 15 },
});
